#!/usr/bin/env node
// Builds the Docusaurus doc tree for one Liquidsoap version.
//
//   node scripts/sync-docs.mjs --version 2.4.5              -> versioned_docs/, committed
//   node scripts/sync-docs.mjs --version dev --bundle <dir>  -> docs/, gitignored
//
// Markdown comes from the git tag; the five reference/settings/protocols files come from
// running the matching docker image, since they are generated by the binary itself.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { resolveIncludes } from './lib/includes.mjs';
import { addExplicitAnchors, slug } from './lib/anchors.mjs';
import { stripEmoji } from './lib/emoji.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const args = process.argv.slice(2);
const arg = (name, dflt) => {
  const i = args.indexOf(`--${name}`);
  return i < 0 ? dflt : args[i + 1];
};
const VERSION = arg('version');
const GENERATED = arg('generated');
const BUNDLE = arg('bundle');
const STRICT = args.includes('--strict');
const SKIP_DOCKER = args.includes('--skip-docker');
const WATCH = args.includes('--watch');
// Re-syncs under --watch overwrite in place. Wiping the tree first makes the Docusaurus
// dev server tear down and re-add every route, which exhausts its file descriptors.
const NO_CLEAN = args.includes('--no-clean');
if (!VERSION) throw new Error('usage: sync-docs.mjs --version <dev|X.Y.Z> [--strict]');

const isDev = VERSION === 'dev';
const OUT = isDev ? path.join(ROOT, 'docs') : path.join(ROOT, `versioned_docs/version-${VERSION}`);
const STATIC_OUT = path.join(ROOT, 'static', `doc-${VERSION}`);

// One curated navigation for every version, filtered below against the pages this version
// actually has. Its labels double as page titles where a heading is too generic.
const sidebarFile = path.join(ROOT, 'sidebars/base.json');
const curatedSidebar = fs.existsSync(sidebarFile)
  ? JSON.parse(fs.readFileSync(sidebarFile, 'utf8'))
  : { docs: [] };
const labels = {};
for (const cat of curatedSidebar.docs) for (const item of cat.items ?? []) labels[item.id] = item.label;

const warnings = [];
const warn = (m) => {
  warnings.push(m);
  console.warn(`  warn: ${m}`);
};

// --- 1. source markdown -------------------------------------------------------------

/**
 * A bundle produced by liquidsoap's own CI: `content/` verbatim from doc/content, plus
 * the five files the binary generates. Preferred for `dev`, because prose and reference
 * then provably come from the same commit -- fetching main's tarball separately could
 * pick up a newer commit than the one that produced the reference.
 */
function useBundle(dir) {
  const resolved = path.resolve(dir);
  const src = path.join(resolved, 'content');
  if (!fs.existsSync(src)) throw new Error(`${resolved}: no content/ directory`);
  writeDevLabel(path.join(resolved, 'version'));
  // Copied rather than used in place: the generated files are installed alongside the
  // prose, and the caller's bundle should not be written to. dereference matters -- a
  // preview bundle links content at the live doc/content tree, and without it the copy
  // is the link, so the generated files land in the source tree. Under --watch that also
  // makes the sync trigger itself.
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'liq-doc-'));
  fs.cpSync(src, path.join(tmp, 'content'), { recursive: true, dereference: true });
  console.log(`  using bundle ${resolved}`);
  return { root: tmp, content: path.join(tmp, 'content'), generated: resolved };
}

function fetchContent() {
  const ref = isDev ? 'refs/heads/main' : `refs/tags/v${VERSION}`;
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'liq-doc-'));
  console.log(`  fetching ${ref}`);
  execFileSync(
    'bash',
    ['-c', `curl -sL https://github.com/savonet/liquidsoap/archive/${ref}.tar.gz | tar xz -C "${tmp}"`],
    { stdio: 'inherit' }
  );
  const root = path.join(tmp, fs.readdirSync(tmp)[0]);
  return { root, content: path.join(root, 'doc/content'), generated: null };
}

/**
 * Write only if the content differs. The dev server reloads a whole version when any of
 * its files change, so a re-sync that rewrote all 129 pages made it reload every version
 * at once and run out of file descriptors. Editing one page should touch one file.
 */
function writeFile(file, data) {
  try {
    if (fs.readFileSync(file, 'utf8') === data) return;
  } catch {
    // Not there yet, or unreadable: write it.
  }
  fs.writeFileSync(file, data);
}

/**
 * The label for the in-development version, derived from liquidsoap's own dune-project
 * version so that it follows the series without anyone editing it: 2.5.0 -> "2.5.x (dev)",
 * and 2.6.0 the day main bumps. Written to a gitignored file that the config reads.
 */
function writeDevLabel(versionFile) {
  const out = path.join(ROOT, 'dev-version.json');
  fs.rmSync(out, { force: true });
  if (!fs.existsSync(versionFile)) {
    warn('bundle carries no version file; the dev version will be labelled "dev"');
    return;
  }
  const raw = fs.readFileSync(versionFile, 'utf8').trim();
  const m = /^(\d+)\.(\d+)\./.exec(raw);
  if (!m) {
    warn(`bundle version "${raw}" is not X.Y.Z; the dev version will be labelled "dev"`);
    return;
  }
  const label = `${m[1]}.${m[2]}.x (dev)`;
  fs.writeFileSync(out, JSON.stringify({ version: raw, label }, null, 2) + '\n');
  console.log(`  dev label: ${label}  (from ${raw})`);
}

// --- 2. generated markdown, from the binary ----------------------------------------

// Mirrors doc/gen_dune.ml. `--no-external-plugins` does not exist before 2.3.0, so it is
// applied conditionally rather than unconditionally.
const lt = (v, other) => {
  const a = v.split('.').map(Number);
  const b = other.split('.').map(Number);
  return a[0] !== b[0] ? a[0] < b[0] : a[1] !== b[1] ? a[1] < b[1] : a[2] < b[2];
};

function generatedTargets(version) {
  // `--no-external-plugins` first appears in 2.3.0 (savonet/liquidsoap#3966).
  const noExternal = lt(version, '2.3.0') ? '' : '--no-external-plugins ';
  return [
    { file: 'reference.md', cmd: '--list-functions-md --disable-deprecated', header: true },
    { file: 'reference-extras.md', cmd: `${noExternal}--list-extra-functions-md --disable-deprecated`, header: true },
    { file: 'reference-deprecated.md', cmd: '--list-deprecated-functions-md --enable-deprecated', header: true },
    { file: 'protocols.md', cmd: '--list-protocols-md --disable-deprecated', header: false },
    { file: 'settings.md', cmd: '--list-settings --disable-deprecated', header: false },
  ];
}

const FILES = generatedTargets('9.9.9').map((t) => t.file);

function install(outDir, contentDir, source) {
  const header = path.join(contentDir, 'reference-header.md');
  for (const t of generatedTargets(isDev ? '9.9.9' : VERSION)) {
    const p = path.join(outDir, t.file);
    // 2.2.5 exits 2 from --list-functions-md while still emitting correct output, so the
    // artifact is validated rather than the exit code.
    const body = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
    if (body.trim().length < 100) throw new Error(`${source}: ${t.file} came back empty`);
    // Docker runs the binary, whose output starts at the first category. A bundle comes
    // from dune, which prepends the header itself -- prefixing it again gave the page two
    // H1s, and the duplicate earned a `{#...-1}` anchor, which an .mdx index parses as a
    // JSX expression and refuses to compile.
    const headerText = t.header && fs.existsSync(header) ? fs.readFileSync(header, 'utf8').trim() : '';
    const prefix = headerText && !body.trimStart().startsWith(headerText) ? headerText + '\n\n' : '';
    fs.writeFileSync(path.join(contentDir, t.file), prefix + body);
  }
}

/** Released version: run the tagged image, which is the only artifact that still exists. */
function generateFromDocker(contentDir) {
  const image = `savonet/liquidsoap:v${VERSION}`;
  const script = generatedTargets(VERSION)
    .map((t) => `liquidsoap ${t.cmd} > /out/${t.file}`)
    .join('\n');
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'liq-gen-'));
  console.log(`  generating ${FILES.length} files from ${image}`);
  execFileSync(
    'docker',
    ['run', '--rm', '-e', 'PAGER=none', '-v', `${outDir}:/out`, '--entrypoint', 'sh', image, '-c', script],
    { stdio: ['ignore', 'inherit', 'inherit'] }
  );
  install(outDir, contentDir, image);
  // 13 images at ~1GB each would exhaust a CI runner's disk.
  try {
    execFileSync('docker', ['image', 'rm', image], { stdio: 'ignore' });
  } catch {}
}

/**
 * `dev` has no usable image: savonet/liquidsoap:main was last pushed in 2022 and still
 * reports 2.1.0, and v2.4.x-latest tracks the release branch rather than main. So the
 * five files come from a directory instead -- the liquidsoap CI artifact in a workflow,
 * or a local `dune build @doc` tree when working by hand.
 */
function generateFromDir(contentDir, dir) {
  const resolved = path.resolve(dir);
  const missing = FILES.filter((f) => !fs.existsSync(path.join(resolved, f)));
  if (missing.length) throw new Error(`${resolved}: missing ${missing.join(', ')}`);
  console.log(`  taking ${FILES.length} generated files from ${resolved}`);
  install(resolved, contentDir, resolved);
}

// --- 3. frontmatter -----------------------------------------------------------------

const escape = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const titleCase = (s) => s.replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

/**
 * A couple of pages carry pandoc frontmatter (`header-includes` with LaTeX macros),
 * sometimes closed with `...` rather than `---`, which Docusaurus' parser rejects. It is
 * meaningless here, so it is dropped rather than merged.
 */
function stripFrontmatter(md) {
  const m = /^---\r?\n([\s\S]*?)\r?\n(?:---|\.\.\.)[ \t]*\r?\n?/.exec(md);
  return m ? md.slice(m[0].length) : md;
}

/**
 * Split into lines tagged with whether they sit inside a fenced code block. Liquidsoap
 * snippets are full of `# comment` lines, and includes are resolved before this runs, so
 * anything scanning for headings must skip fences or it will pick up code comments.
 */
function scan(md) {
  let inFence = false;
  return md.split('\n').map((line) => {
    const isFence = /^\s*(```|~~~)/.test(line);
    if (isFence) inFence = !inFence;
    return { line, code: inFence || isFence };
  });
}

// A leading heading of "Introduction"/"Basics" says nothing in a <title> or a search
// result. Those pages fall back to the curated sidebar label instead.
const GENERIC = new Set(['introduction', 'basics', 'overview', 'description', 'presentation']);

/** Hoist the leading `# Title` into frontmatter and derive a real per-page description. */
function addFrontmatter(md, fallbackTitle, label) {
  md = stripFrontmatter(md);
  const rows = scan(md);

  // Pages are inconsistent about whether their leading heading is `#` or `##`, so the
  // first heading of any level is treated as the page title and lifted out of the body.
  let title = titleCase(fallbackTitle);
  const h1 = rows.findIndex((r) => !r.code && /^#{1,6}\s+/.test(r.line));
  if (h1 >= 0) {
    title = rows[h1].line
      .replace(/^#{1,6}\s+/, '')
      .replace(/\s*\{#[^}]+\}\s*$/, '')
      .replace(/`/g, '')
      .trim();
    rows.splice(h1, 1);
    while (rows[h1] && rows[h1].line.trim() === '') rows.splice(h1, 1);
  }
  if (label && (h1 < 0 || GENERIC.has(title.toLowerCase()))) title = label;
  const body = rows.map((r) => r.line).join('\n');

  // First real prose paragraph, ignoring anything inside a fence.
  let description = '';
  let para = [];
  for (const r of scan(body).concat({ line: '', code: false })) {
    if (r.code) {
      para = [];
      continue;
    }
    if (r.line.trim() === '') {
      const p = para.join(' ').trim();
      para = [];
      if (!p || /^[#>|\-*+]|^!\[|^\d+\./.test(p)) continue;
      description = p
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/[`*_]/g, '')
        .replace(/\s+/g, ' ')
        .trim();
      break;
    }
    para.push(r.line);
  }
  if (description.length > 155) description = description.slice(0, 152).replace(/\s\S*$/, '') + '…';

  const fm = ['---', `title: "${escape(title)}"`];
  if (description) fm.push(`description: "${escape(description)}"`);
  // The nav keeps the short curated wording even when the page title is more descriptive.
  if (label && label !== title) fm.push(`sidebar_label: "${escape(label)}"`);
  fm.push('---', '');
  return fm.join('\n') + body;
}

// --- 4. reference split -------------------------------------------------------------

// 1.6MB and 1.9MB single pages are the bulk of all doc bytes, are unusable on mobile, and
// are what makes a full 13-version build untenable. Split at each `## Category`.
function splitReference(md, name, outDir, anchorMap) {
  const { md: anchored, ids } = addExplicitAnchors(md);
  const lines = anchored.split('\n');
  const dir = path.join(outDir, name);
  fs.mkdirSync(dir, { recursive: true });

  const h2 = [];
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^(```|~~~)/.test(line)) inFence = !inFence;
    if (!inFence && /^##\s+(?!#)/.test(line)) h2.push(i);
  });

  const intro = lines.slice(0, h2[0] ?? lines.length).join('\n');
  const sections = h2.map((start, k) => ({
    start,
    end: (h2[k + 1] ?? lines.length) - 1,
    heading: lines[start].replace(/^##\s+/, '').replace(/\s*\{#[^}]+\}\s*$/, '').trim(),
  }));

  const entries = [];
  const functions = [];
  for (const s of sections) {
    const pageSlug = slug(s.heading);
    const chunk = lines.slice(s.start, s.end + 1);
    chunk[0] = `# ${s.heading}`; // promote to page title
    let out = chunk.join('\n');
    out = addFrontmatter(out, s.heading);
    writeFile(path.join(dir, `${pageSlug}.md`), out);
    entries.push({ slug: pageSlug, heading: s.heading, count: 0 });
    // Every heading inside this section now lives on this page.
    for (const id of ids.filter((x) => x.level >= 2)) {
      const within = lines.findIndex((l) => l.includes(`{#${id.id}}`));
      if (within >= s.start && within <= s.end) anchorMap[id.id] = pageSlug;
    }

    // Each `### `name`` is one function; the paragraph under it is its summary. Collected
    // here so the index page can offer search without loading every category page.
    for (let i = s.start; i <= s.end; i++) {
      const m = /^###\s+(.*?)\s*\{#(.+)\}\s*$/.exec(lines[i]);
      if (!m) continue;
      let description = '';
      for (let j = i + 1; j <= s.end; j++) {
        const line = lines[j].trim();
        if (!line) continue;
        if (/^#{1,6}\s/.test(line)) break;
        if (line === 'Type:' || line === 'Arguments:' || line.startsWith('```')) break;
        description = line.replace(/`/g, '');
        break;
      }
      functions.push({
        name: m[1].replace(/`/g, ''),
        anchor: m[2],
        page: pageSlug,
        category: s.heading,
        description,
      });
      entries.at(-1).count++;
    }
  }

  fs.mkdirSync(STATIC_OUT, { recursive: true });
  writeFile(
    path.join(STATIC_OUT, `${name}-index.json`),
    JSON.stringify({
      base: `/doc-${VERSION}/${name}`,
      categories: entries.map((e) => ({ slug: e.slug, label: e.heading, count: e.count })),
      functions,
      // Anchor -> owning page, so the index can forward deep links from the old
      // monolithic page (/doc-<v>/reference.html#output.icecast) to where the anchor
      // now lives. A separate redirect stub cannot: Docusaurus emits this page at
      // exactly that URL and would overwrite it.
      anchors: anchorMap,
    })
  );

  // The index is .mdx so it can host the search component; `markdown.format: 'detect'`
  // keeps every other reference page on CommonMark. The generated bullet list of
  // categories is dropped -- the component renders them as a grid with counts.
  // Explicit anchors go too: MDX reads `{...}` as an expression and fails to compile.
  // Nothing deep-links to a heading on this page -- the function anchors are all on the
  // category pages, which are .md.
  const body = intro
    .replace(/^\s*-\s+\[.*\]\(#.*\)\s*$/gm, '')
    .replace(/[ \t]*\{#[\w.-]+\}[ \t]*$/gm, '')
    .replace(/\n{3,}/g, '\n\n');
  const index = addFrontmatter(
    `${body.trim()}\n\n<ApiIndex src="/doc-${VERSION}/${name}-index.json" />\n`,
    name
  ).replace(/^(---\n[\s\S]*?\n---\n)/, `$1\nimport ApiIndex from '@site/src/components/ApiIndex';\n\n`);
  writeFile(path.join(dir, 'index.mdx'), index);
  return entries;
}

// --- main ---------------------------------------------------------------------------

console.log(`sync ${VERSION}`);
if (!NO_CLEAN) fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const { root, content, generated } = BUNDLE ? useBundle(BUNDLE) : fetchContent();
if (!SKIP_DOCKER) {
  const dir = generated ?? GENERATED;
  if (dir) generateFromDir(content, dir);
  else if (isDev)
    throw new Error(
      'dev needs --bundle <dir> (content/ plus the five generated .md files, as built by\n' +
        "liquidsoap's CI), or --generated <dir> to supply just the generated five.\n" +
        'Locally, after `dune build @doc` in a liquidsoap checkout:\n' +
        '  --generated <liquidsoap>/_build/default/doc\n' +
        'There is no usable docker image: savonet/liquidsoap:main is stale (2.1.0, 2022).'
    );
  else generateFromDocker(content);
}

const liqDir = path.join(content, 'liq');
const SPLIT = new Set(['reference.md', 'reference-extras.md', 'reference-deprecated.md']);
const anchorMaps = {};
let pages = 0;

for (const entry of fs.readdirSync(content, { withFileTypes: true })) {
  const src = path.join(content, entry.name);
  // stat rather than the Dirent: content/images is a symlink to ../orig/images, so
  // Dirent.isDirectory() is false for it. A bundle that ships content/ alone leaves that
  // link dangling, which is a missing asset rather than a reason to stop.
  let stat;
  try {
    stat = fs.statSync(src);
  } catch {
    warn(`${entry.name}: unresolved link in doc content, skipped`);
    continue;
  }

  if (stat.isDirectory()) {
    if (entry.name === 'images') {
      fs.cpSync(src, path.join(OUT, 'images'), { recursive: true, dereference: true });
    }
    continue; // `liq/` is consumed by resolveIncludes, never shipped
  }

  // Assets are not always under images/: main keeps jack-patchbay.png beside jack.md and
  // references it relatively. Anything that is not markdown is carried across as-is --
  // except dotfiles, which belong to liquidsoap's repository, not to the docs. Copying
  // doc/content/.gitignore, which lists the generated files, quietly stopped protocols.md
  // and settings.md from being committed here and broke the build.
  if (!entry.name.endsWith('.md')) {
    if (entry.name.startsWith('.')) continue;
    fs.copyFileSync(src, path.join(OUT, entry.name));
    continue;
  }
  if (entry.name === 'reference-header.md') continue; // a fragment, not a page

  let md = fs.readFileSync(src, 'utf8');
  md = resolveIncludes(md, liqDir, `${VERSION}/${entry.name}`, warn);

  if (SPLIT.has(entry.name)) {
    const name = entry.name.replace(/\.md$/, '');
    const map = {};
    const entries = splitReference(md, name, OUT, map);
    anchorMaps[name] = map;
    pages += entries.length + 1;
    console.log(`  split ${entry.name} -> ${entries.length} pages`);
    continue;
  }

  const id = entry.name.replace(/\.md$/, '');
  md = addExplicitAnchors(md).md;
  md = stripEmoji(md);
  md = addFrontmatter(md, id, labels[id]);
  // Docusaurus would treat index.md as the version root and emit /doc-<v>.html. The
  // current site publishes /doc-<v>/index.html (and serves /doc-<v>/ from it), so the
  // slug is pinned to keep that URL.
  if (id === 'index') md = md.replace(/^---\n/, '---\nslug: /index.html\n');
  writeFile(path.join(OUT, entry.name), md);
  pages++;
}

// Only a fetched tarball is ours to delete; a bundle belongs to the caller.
if (root) fs.rmSync(root, { recursive: true, force: true });

// --- cross-page links -----------------------------------------------------------------

// Pages link to each other as `[quickstart](quick_start.html)`, which the pandoc build
// resolved by filename. Those still land on a real file here, but Docusaurus resolves
// links against routes, which are extensionless, so it cannot verify them -- 167 unusable
// warnings per version, and real breakage hidden among them. Rewriting to `./page.md`
// makes them first-class: checked at build time and routed client-side.
{
  let rewritten = 0;
  // Docusaurus resolves a markdown link by the file it names, so the extension has to be
  // the real one: reference indexes are .mdx (they host the search component).
  const resolve = (id) => {
    for (const ext of ['.md', '.mdx']) if (fs.existsSync(path.join(OUT, id + ext))) return id + ext;
    return null;
  };

  for (const entry of fs.readdirSync(OUT, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const file = path.join(OUT, entry.name);
    const before = fs.readFileSync(file, 'utf8');

    const after = before.replace(/\]\(([\w.-]+)\.html(#[^)]*)?\)/g, (whole, target, hash = '') => {
      // The reference pages were split, so a link into them has to name the category page
      // that now owns the anchor.
      if (anchorMaps[target]) {
        const anchor = hash.slice(1);
        const page = anchorMaps[target][anchor];
        const file = page ? resolve(`${target}/${page}`) : resolve(`${target}/index`);
        if (file) {
          rewritten++;
          return `](./${file}${page ? `#${anchor}` : ''})`;
        }
      }
      const file = resolve(target);
      if (file) {
        rewritten++;
        return `](./${file}${hash})`;
      }
      warn(`${entry.name}: link to "${target}.html", which has no page in ${VERSION}`);
      return whole;
    });

    if (after !== before) fs.writeFileSync(file, after);
  }
  console.log(`  rewrote ${rewritten} cross-page links`);
}

// A pandoc-include directive that the fence regex fails to match produces no warning at
// all -- it just silently survives into the output. Assert none did.
const leaked = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.md') && /^```\{\./m.test(fs.readFileSync(p, 'utf8'))) leaked.push(p);
  }
};
walk(OUT);
if (leaked.length) {
  console.error(`\nunresolved pandoc-include fences in ${leaked.length} file(s):`);
  for (const p of leaked.slice(0, 10)) console.error(`  ${path.relative(ROOT, p)}`);
  process.exit(1);
}

// --- sidebar -------------------------------------------------------------------------

// The curated sidebars still name pages that no longer exist -- `dolebrai` and
// `replay_gain` are live 404s on the current site. Docusaurus hard-errors on those, so
// they are dropped with a warning instead of taking the whole build down.
const emitted = new Set();
const collect = (dir, prefix = '') => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) collect(path.join(dir, e.name), `${prefix}${e.name}/`);
    else if (/\.mdx?$/.test(e.name)) emitted.add(prefix + e.name.replace(/\.mdx?$/, ''));
  }
};
collect(OUT);

let dropped = 0;
const linked = new Set();
const keep = (id) => {
  if (emitted.has(id)) {
    linked.add(id);
    return true;
  }
  warn(`sidebar entry "${id}" has no page`);
  dropped++;
  return false;
};

const sidebar = [];
for (const node of curatedSidebar.docs) {
  if (node.type === 'doc') {
    if (keep(node.id)) sidebar.push(node);
    continue;
  }
  const items = (node.items ?? []).filter((item) => keep(item.id));
  // A category may also link to a page of its own (the "Install" header does).
  const link = node.link && keep(node.link.id) ? node.link : undefined;
  if (items.length || link) sidebar.push({ ...node, items, ...(link ? { link } : { link: undefined }) });
}
const orphans = [...emitted].filter((id) => !linked.has(id) && !id.includes('/'));

const sidebarOut = isDev
  ? path.join(ROOT, 'sidebars.dev.json')
  : path.join(ROOT, `versioned_sidebars/version-${VERSION}-sidebars.json`);
fs.mkdirSync(path.dirname(sidebarOut), { recursive: true });
writeFile(sidebarOut, JSON.stringify({ docs: sidebar }, null, 2) + '\n');

console.log(`  ${pages} pages, ${warnings.length} warnings`);
console.log(`  sidebar: ${sidebar.length} categories, ${linked.size} entries, ${dropped} dropped`);
if (orphans.length) console.log(`  ${orphans.length} pages in no sidebar: ${orphans.join(', ')}`);
if (STRICT && warnings.length) {
  console.error(`\n${warnings.length} warning(s) with --strict`);
  process.exit(1);
}

// --- watch ----------------------------------------------------------------------------

// For previewing documentation edits: re-sync whenever the source changes, so the
// Docusaurus dev server -- which already watches docs/ -- hot-reloads them. The sync is
// re-run as a child process rather than refactored into a loop, so a crash in one pass
// cannot leave this one wedged.
if (WATCH) {
  if (!BUNDLE) throw new Error('--watch needs --bundle <dir>');
  // Resolved, because a preview bundle points content at the live doc/content tree by
  // symlink so that edits there are what we are watching for.
  const target = fs.realpathSync(path.resolve(BUNDLE, 'content'));
  console.log(`\nwatching ${target}`);

  let timer = null;
  let running = false;
  let again = false;

  const resync = () => {
    if (running) {
      again = true;
      return;
    }
    running = true;
    const rerun = [...args.filter((a) => a !== '--watch'), '--no-clean'];
    const child = spawn(process.execPath, [fileURLToPath(import.meta.url), ...rerun], {
      stdio: 'inherit',
    });
    child.on('exit', () => {
      running = false;
      if (again) {
        again = false;
        resync();
      }
    });
  };

  fs.watch(target, { recursive: true }, (_event, file) => {
    if (!file || !/\.(md|liq|png|jpg|svg)$/.test(file)) return;
    clearTimeout(timer);
    // Editors write in bursts; one re-sync per burst is enough.
    timer = setTimeout(() => {
      console.log(`\nchanged: ${file}`);
      resync();
    }, 300);
  });
}
