#!/usr/bin/env node
// Builds the Docusaurus doc tree for one Liquidsoap version.
//
//   node scripts/sync-docs.mjs --version 2.4.5   -> versioned_docs/, committed via PR
//   node scripts/sync-docs.mjs --version dev     -> docs/, gitignored, rebuilt each build
//
// Markdown comes from the git tag; the five reference/settings/protocols files come from
// running the matching docker image, since they are generated by the binary itself.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { resolveIncludes } from './lib/includes.mjs';
import { addExplicitAnchors, slug } from './lib/anchors.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const args = process.argv.slice(2);
const arg = (name, dflt) => {
  const i = args.indexOf(`--${name}`);
  return i < 0 ? dflt : args[i + 1];
};
const VERSION = arg('version');
const GENERATED = arg('generated');
const STRICT = args.includes('--strict');
const SKIP_DOCKER = args.includes('--skip-docker');
if (!VERSION) throw new Error('usage: sync-docs.mjs --version <dev|X.Y.Z> [--strict]');

const isDev = VERSION === 'dev';
const OUT = isDev ? path.join(ROOT, 'docs') : path.join(ROOT, `versioned_docs/version-${VERSION}`);
const STATIC_OUT = path.join(ROOT, 'static', `doc-${VERSION}`);

// The old per-version templates carry curated nav labels; they are better page titles
// than a generic leading heading, and they keep the nav wording stable.
const sidebarFile = path.join(ROOT, `sidebars/version-${VERSION}.json`);
const curatedSidebar = fs.existsSync(sidebarFile)
  ? JSON.parse(fs.readFileSync(sidebarFile, 'utf8'))
  : { docs: [] };
const labels = {};
for (const cat of curatedSidebar.docs) for (const item of cat.items ?? []) labels[item.id] = item.label;

const warnings = [];
const warn = (m) => {
  warnings.push(m);
  console.warn(`  warn: ${m}`);
};

// --- 1. source markdown, from the tag ----------------------------------------------

function fetchContent() {
  const ref = isDev ? 'refs/heads/main' : `refs/tags/v${VERSION}`;
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'liq-doc-'));
  console.log(`  fetching ${ref}`);
  execFileSync(
    'bash',
    ['-c', `curl -sL https://github.com/savonet/liquidsoap/archive/${ref}.tar.gz | tar xz -C "${tmp}"`],
    { stdio: 'inherit' }
  );
  const root = path.join(tmp, fs.readdirSync(tmp)[0]);
  return { root, content: path.join(root, 'doc/content') };
}

// --- 2. generated markdown, from the binary ----------------------------------------

// Mirrors doc/gen_dune.ml. `--no-external-plugins` does not exist before 2.3.0, so it is
// applied conditionally rather than unconditionally.
const lt = (v, other) => {
  const a = v.split('.').map(Number);
  const b = other.split('.').map(Number);
  return a[0] !== b[0] ? a[0] < b[0] : a[1] !== b[1] ? a[1] < b[1] : a[2] < b[2];
};

function generatedTargets(version) {
  // `--no-external-plugins` first appears in 2.3.0 (savonet/liquidsoap#3966).
  const noExternal = lt(version, '2.3.0') ? '' : '--no-external-plugins ';
  return [
    { file: 'reference.md', cmd: '--list-functions-md --disable-deprecated', header: true },
    { file: 'reference-extras.md', cmd: `${noExternal}--list-extra-functions-md --disable-deprecated`, header: true },
    { file: 'reference-deprecated.md', cmd: '--list-deprecated-functions-md --enable-deprecated', header: true },
    { file: 'protocols.md', cmd: '--list-protocols-md --disable-deprecated', header: false },
    { file: 'settings.md', cmd: '--list-settings --disable-deprecated', header: false },
  ];
}

const FILES = generatedTargets('9.9.9').map((t) => t.file);

function install(outDir, contentDir, source) {
  const header = path.join(contentDir, 'reference-header.md');
  for (const t of generatedTargets(isDev ? '9.9.9' : VERSION)) {
    const p = path.join(outDir, t.file);
    // 2.2.5 exits 2 from --list-functions-md while still emitting correct output, so the
    // artifact is validated rather than the exit code.
    const body = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
    if (body.trim().length < 100) throw new Error(`${source}: ${t.file} came back empty`);
    const prefix = t.header && fs.existsSync(header) ? fs.readFileSync(header, 'utf8') + '\n\n' : '';
    fs.writeFileSync(path.join(contentDir, t.file), prefix + body);
  }
}

/** Released version: run the tagged image, which is the only artifact that still exists. */
function generateFromDocker(contentDir) {
  const image = `savonet/liquidsoap:v${VERSION}`;
  const script = generatedTargets(VERSION)
    .map((t) => `liquidsoap ${t.cmd} > /out/${t.file}`)
    .join('\n');
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'liq-gen-'));
  console.log(`  generating ${FILES.length} files from ${image}`);
  execFileSync(
    'docker',
    ['run', '--rm', '-e', 'PAGER=none', '-v', `${outDir}:/out`, '--entrypoint', 'sh', image, '-c', script],
    { stdio: ['ignore', 'inherit', 'inherit'] }
  );
  install(outDir, contentDir, image);
  // 13 images at ~1GB each would exhaust a CI runner's disk.
  try {
    execFileSync('docker', ['image', 'rm', image], { stdio: 'ignore' });
  } catch {}
}

/**
 * `dev` has no usable image: savonet/liquidsoap:main was last pushed in 2022 and still
 * reports 2.1.0, and v2.4.x-latest tracks the release branch rather than main. So the
 * five files come from a directory instead -- the liquidsoap CI artifact in a workflow,
 * or a local `dune build @doc` tree when working by hand.
 */
function generateFromDir(contentDir, dir) {
  const resolved = path.resolve(dir);
  const missing = FILES.filter((f) => !fs.existsSync(path.join(resolved, f)));
  if (missing.length) throw new Error(`${resolved}: missing ${missing.join(', ')}`);
  console.log(`  taking ${FILES.length} generated files from ${resolved}`);
  install(resolved, contentDir, resolved);
}

// --- 3. frontmatter -----------------------------------------------------------------

const escape = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const titleCase = (s) => s.replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

/**
 * A couple of pages carry pandoc frontmatter (`header-includes` with LaTeX macros),
 * sometimes closed with `...` rather than `---`, which Docusaurus' parser rejects. It is
 * meaningless here, so it is dropped rather than merged.
 */
function stripFrontmatter(md) {
  const m = /^---\r?\n([\s\S]*?)\r?\n(?:---|\.\.\.)[ \t]*\r?\n?/.exec(md);
  return m ? md.slice(m[0].length) : md;
}

/**
 * Split into lines tagged with whether they sit inside a fenced code block. Liquidsoap
 * snippets are full of `# comment` lines, and includes are resolved before this runs, so
 * anything scanning for headings must skip fences or it will pick up code comments.
 */
function scan(md) {
  let inFence = false;
  return md.split('\n').map((line) => {
    const isFence = /^\s*(```|~~~)/.test(line);
    if (isFence) inFence = !inFence;
    return { line, code: inFence || isFence };
  });
}

// A leading heading of "Introduction"/"Basics" says nothing in a <title> or a search
// result. Those pages fall back to the curated sidebar label instead.
const GENERIC = new Set(['introduction', 'basics', 'overview', 'description', 'presentation']);

/** Hoist the leading `# Title` into frontmatter and derive a real per-page description. */
function addFrontmatter(md, fallbackTitle, label) {
  md = stripFrontmatter(md);
  const rows = scan(md);

  // Pages are inconsistent about whether their leading heading is `#` or `##`, so the
  // first heading of any level is treated as the page title and lifted out of the body.
  let title = titleCase(fallbackTitle);
  const h1 = rows.findIndex((r) => !r.code && /^#{1,6}\s+/.test(r.line));
  if (h1 >= 0) {
    title = rows[h1].line
      .replace(/^#{1,6}\s+/, '')
      .replace(/\s*\{#[^}]+\}\s*$/, '')
      .replace(/`/g, '')
      .trim();
    rows.splice(h1, 1);
    while (rows[h1] && rows[h1].line.trim() === '') rows.splice(h1, 1);
  }
  if (label && (h1 < 0 || GENERIC.has(title.toLowerCase()))) title = label;
  const body = rows.map((r) => r.line).join('\n');

  // First real prose paragraph, ignoring anything inside a fence.
  let description = '';
  let para = [];
  for (const r of scan(body).concat({ line: '', code: false })) {
    if (r.code) {
      para = [];
      continue;
    }
    if (r.line.trim() === '') {
      const p = para.join(' ').trim();
      para = [];
      if (!p || /^[#>|\-*+]|^!\[|^\d+\./.test(p)) continue;
      description = p
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/[`*_]/g, '')
        .replace(/\s+/g, ' ')
        .trim();
      break;
    }
    para.push(r.line);
  }
  if (description.length > 155) description = description.slice(0, 152).replace(/\s\S*$/, '') + '…';

  const fm = ['---', `title: "${escape(title)}"`];
  if (description) fm.push(`description: "${escape(description)}"`);
  // The nav keeps the short curated wording even when the page title is more descriptive.
  if (label && label !== title) fm.push(`sidebar_label: "${escape(label)}"`);
  fm.push('---', '');
  return fm.join('\n') + body;
}

// --- 4. reference split -------------------------------------------------------------

// 1.6MB and 1.9MB single pages are the bulk of all doc bytes, are unusable on mobile, and
// are what makes a full 13-version build untenable. Split at each `## Category`.
function splitReference(md, name, outDir, anchorMap) {
  const { md: anchored, ids } = addExplicitAnchors(md);
  const lines = anchored.split('\n');
  const dir = path.join(outDir, name);
  fs.mkdirSync(dir, { recursive: true });

  const h2 = [];
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^(```|~~~)/.test(line)) inFence = !inFence;
    if (!inFence && /^##\s+(?!#)/.test(line)) h2.push(i);
  });

  const intro = lines.slice(0, h2[0] ?? lines.length).join('\n');
  const sections = h2.map((start, k) => ({
    start,
    end: (h2[k + 1] ?? lines.length) - 1,
    heading: lines[start].replace(/^##\s+/, '').replace(/\s*\{#[^}]+\}\s*$/, '').trim(),
  }));

  const entries = [];
  const functions = [];
  for (const s of sections) {
    const pageSlug = slug(s.heading);
    const chunk = lines.slice(s.start, s.end + 1);
    chunk[0] = `# ${s.heading}`; // promote to page title
    let out = chunk.join('\n');
    out = addFrontmatter(out, s.heading);
    fs.writeFileSync(path.join(dir, `${pageSlug}.md`), out);
    entries.push({ slug: pageSlug, heading: s.heading, count: 0 });
    // Every heading inside this section now lives on this page.
    for (const id of ids.filter((x) => x.level >= 2)) {
      const within = lines.findIndex((l) => l.includes(`{#${id.id}}`));
      if (within >= s.start && within <= s.end) anchorMap[id.id] = pageSlug;
    }

    // Each `### `name`` is one function; the paragraph under it is its summary. Collected
    // here so the index page can offer search without loading every category page.
    for (let i = s.start; i <= s.end; i++) {
      const m = /^###\s+(.*?)\s*\{#(.+)\}\s*$/.exec(lines[i]);
      if (!m) continue;
      let description = '';
      for (let j = i + 1; j <= s.end; j++) {
        const line = lines[j].trim();
        if (!line) continue;
        if (/^#{1,6}\s/.test(line)) break;
        if (line === 'Type:' || line === 'Arguments:' || line.startsWith('```')) break;
        description = line.replace(/`/g, '');
        break;
      }
      functions.push({
        name: m[1].replace(/`/g, ''),
        anchor: m[2],
        page: pageSlug,
        category: s.heading,
        description,
      });
      entries.at(-1).count++;
    }
  }

  fs.mkdirSync(STATIC_OUT, { recursive: true });
  fs.writeFileSync(
    path.join(STATIC_OUT, `${name}-index.json`),
    JSON.stringify({
      base: `/doc-${VERSION}/${name}`,
      categories: entries.map((e) => ({ slug: e.slug, label: e.heading, count: e.count })),
      functions,
      // Anchor -> owning page, so the index can forward deep links from the old
      // monolithic page (/doc-<v>/reference.html#output.icecast) to where the anchor
      // now lives. A separate redirect stub cannot: Docusaurus emits this page at
      // exactly that URL and would overwrite it.
      anchors: anchorMap,
    })
  );

  // The index is .mdx so it can host the search component; `markdown.format: 'detect'`
  // keeps every other reference page on CommonMark. The generated bullet list of
  // categories is dropped -- the component renders them as a grid with counts.
  const body = intro.replace(/^\s*-\s+\[.*\]\(#.*\)\s*$/gm, '').replace(/\n{3,}/g, '\n\n');
  const index = addFrontmatter(
    `${body.trim()}\n\n<ApiIndex src="/doc-${VERSION}/${name}-index.json" />\n`,
    name
  ).replace(/^(---\n[\s\S]*?\n---\n)/, `$1\nimport ApiIndex from '@site/src/components/ApiIndex';\n\n`);
  fs.writeFileSync(path.join(dir, 'index.mdx'), index);
  return entries;
}

// --- main ---------------------------------------------------------------------------

console.log(`sync ${VERSION}`);
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const { root, content } = fetchContent();
if (!SKIP_DOCKER) {
  if (GENERATED) generateFromDir(content, GENERATED);
  else if (isDev)
    throw new Error(
      'dev needs --generated <dir> holding the five generated .md files.\n' +
        'In CI that is the liquidsoap doc artifact; locally it is\n' +
        '  <liquidsoap>/_build/default/doc  after `dune build @doc`.\n' +
        'There is no usable docker image: savonet/liquidsoap:main is stale (2.1.0, 2022).'
    );
  else generateFromDocker(content);
}

const liqDir = path.join(content, 'liq');
const SPLIT = new Set(['reference.md', 'reference-extras.md', 'reference-deprecated.md']);
const anchorMaps = {};
let pages = 0;

for (const entry of fs.readdirSync(content, { withFileTypes: true })) {
  const src = path.join(content, entry.name);
  if (entry.isDirectory()) {
    if (entry.name === 'images') fs.cpSync(src, path.join(OUT, 'images'), { recursive: true });
    continue; // `liq/` is consumed by resolveIncludes, never shipped
  }
  if (!entry.name.endsWith('.md')) continue;
  if (entry.name === 'reference-header.md') continue; // a fragment, not a page

  let md = fs.readFileSync(src, 'utf8');
  md = resolveIncludes(md, liqDir, `${VERSION}/${entry.name}`, warn);

  if (SPLIT.has(entry.name)) {
    const name = entry.name.replace(/\.md$/, '');
    const map = {};
    const entries = splitReference(md, name, OUT, map);
    anchorMaps[name] = map;
    pages += entries.length + 1;
    console.log(`  split ${entry.name} -> ${entries.length} pages`);
    continue;
  }

  const id = entry.name.replace(/\.md$/, '');
  md = addExplicitAnchors(md).md;
  md = addFrontmatter(md, id, labels[id]);
  // Docusaurus would treat index.md as the version root and emit /doc-<v>.html. The
  // current site publishes /doc-<v>/index.html (and serves /doc-<v>/ from it), so the
  // slug is pinned to keep that URL.
  if (id === 'index') md = md.replace(/^---\n/, '---\nslug: /index.html\n');
  fs.writeFileSync(path.join(OUT, entry.name), md);
  pages++;
}

fs.rmSync(root, { recursive: true, force: true });

// A pandoc-include directive that the fence regex fails to match produces no warning at
// all -- it just silently survives into the output. Assert none did.
const leaked = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.md') && /^```\{\./m.test(fs.readFileSync(p, 'utf8'))) leaked.push(p);
  }
};
walk(OUT);
if (leaked.length) {
  console.error(`\nunresolved pandoc-include fences in ${leaked.length} file(s):`);
  for (const p of leaked.slice(0, 10)) console.error(`  ${path.relative(ROOT, p)}`);
  process.exit(1);
}

// --- sidebar -------------------------------------------------------------------------

// The curated sidebars still name pages that no longer exist -- `dolebrai` and
// `replay_gain` are live 404s on the current site. Docusaurus hard-errors on those, so
// they are dropped with a warning instead of taking the whole build down.
const emitted = new Set();
const collect = (dir, prefix = '') => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) collect(path.join(dir, e.name), `${prefix}${e.name}/`);
    else if (/\.mdx?$/.test(e.name)) emitted.add(prefix + e.name.replace(/\.mdx?$/, ''));
  }
};
collect(OUT);

let dropped = 0;
const linked = new Set();
const keep = (id) => {
  if (emitted.has(id)) {
    linked.add(id);
    return true;
  }
  warn(`sidebar entry "${id}" has no page`);
  dropped++;
  return false;
};

const sidebar = [];
for (const node of curatedSidebar.docs) {
  if (node.type === 'doc') {
    if (keep(node.id)) sidebar.push(node);
    continue;
  }
  const items = (node.items ?? []).filter((item) => keep(item.id));
  // A category may also link to a page of its own (the "Install" header does).
  const link = node.link && keep(node.link.id) ? node.link : undefined;
  if (items.length || link) sidebar.push({ ...node, items, ...(link ? { link } : { link: undefined }) });
}
const orphans = [...emitted].filter((id) => !linked.has(id) && !id.includes('/'));

const sidebarOut = isDev
  ? path.join(ROOT, 'sidebars.dev.json')
  : path.join(ROOT, `versioned_sidebars/version-${VERSION}-sidebars.json`);
fs.mkdirSync(path.dirname(sidebarOut), { recursive: true });
fs.writeFileSync(sidebarOut, JSON.stringify({ docs: sidebar }, null, 2) + '\n');

console.log(`  ${pages} pages, ${warnings.length} warnings`);
console.log(`  sidebar: ${sidebar.length} categories, ${linked.size} entries, ${dropped} dropped`);
if (orphans.length) console.log(`  ${orphans.length} pages in no sidebar: ${orphans.join(', ')}`);
if (STRICT && warnings.length) {
  console.error(`\n${warnings.length} warning(s) with --strict`);
  process.exit(1);
}
